services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: ai-study-qdrant

    ports:
      - "6333:6333"
      - "6334:6334"

    volumes:
      - ./docker/qdrant_storage:/qdrant/storage

    restart: unless-stopped